import { NextResponse } from "next/server";

export type ApiErrorCode =
  | "UNAUTHORIZED"
  | "VALIDATION_ERROR"
  | "EMAIL_ALREADY_EXISTS"
  | "NO_FILE_UPLOADED"
  | "FILE_TOO_LARGE"
  | "UNSUPPORTED_FILE_TYPE"
  | "FILE_UNREADABLE"
  | "FILE_TEXT_TOO_SHORT"
  | "JOB_POSTING_TEXT_TOO_SHORT"
  | "RESUME_NOT_FOUND"
  | "JOB_POSTING_NOT_FOUND"
  | "ANALYSIS_NOT_FOUND"
  | "VERSION_NOT_FOUND"
  | "APPLICATION_NOT_FOUND"
  | "AI_PARSING_FAILED"
  | "AI_ANALYSIS_FAILED"
  | "AI_OPTIMIZATION_FAILED"
  | "GENERIC_ERROR";

const STATUS_BY_CODE: Record<ApiErrorCode, number> = {
  UNAUTHORIZED: 401,
  VALIDATION_ERROR: 400,
  EMAIL_ALREADY_EXISTS: 409,
  NO_FILE_UPLOADED: 400,
  FILE_TOO_LARGE: 400,
  UNSUPPORTED_FILE_TYPE: 400,
  FILE_UNREADABLE: 422,
  FILE_TEXT_TOO_SHORT: 422,
  JOB_POSTING_TEXT_TOO_SHORT: 400,
  RESUME_NOT_FOUND: 404,
  JOB_POSTING_NOT_FOUND: 404,
  ANALYSIS_NOT_FOUND: 404,
  VERSION_NOT_FOUND: 404,
  APPLICATION_NOT_FOUND: 404,
  AI_PARSING_FAILED: 502,
  AI_ANALYSIS_FAILED: 502,
  AI_OPTIMIZATION_FAILED: 502,
  GENERIC_ERROR: 500,
};

export function apiError(code: ApiErrorCode, status: number = STATUS_BY_CODE[code]) {
  return NextResponse.json({ error: code }, { status });
}
